/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./App.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-background": "#dae2fd",
        "primary-fixed-dim": "#ddb7ff",
        "surface-container-low": "#131b2e",
        "on-primary-fixed-variant": "#6900b3",
        "on-secondary": "#00363e",
        "error": "#ffb4ab",
        "surface-container": "#171f33",
        "on-secondary-fixed-variant": "#004e5a",
        "on-primary": "#490080",
        "on-secondary-fixed": "#001f25",
        "on-surface": "#dae2fd",
        "surface-bright": "#31394d",
        "tertiary-fixed": "#ffd8e7",
        "tertiary": "#ffafd3",
        "surface-container-highest": "#2d3449",
        "secondary": "#5de6ff",
        "surface-tint": "#ddb7ff",
        "primary": "#ddb7ff",
        "outline-variant": "#4d4354",
        "error-container": "#93000a",
        "on-secondary-container": "#00515d",
        "secondary-fixed": "#a2eeff",
        "on-error": "#690005",
        "secondary-fixed-dim": "#2fd9f4",
        "primary-fixed": "#f0dbff",
        "on-surface-variant": "#cfc2d6",
        "on-tertiary-fixed": "#3d0026",
        "on-primary-container": "#400071",
        "surface-variant": "#2d3449",
        "outline": "#988d9f",
        "surface-dim": "#0b1326",
        "secondary-container": "#00cbe6",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dae2fd",
        "background": "#0b1326",
        "inverse-primary": "#842bd2",
        "surface-container-lowest": "#060e20",
        "inverse-on-surface": "#283044",
        "surface-container-high": "#222a3d",
        "on-primary-fixed": "#2c0051",
        "tertiary-fixed-dim": "#ffafd3",
        "primary-container": "#b76dff",
        "on-tertiary": "#620040",
        "on-tertiary-fixed-variant": "#85145a",
        "surface": "#0b1326",
        "on-tertiary-container": "#560038",
        "tertiary-container": "#e364a7",
      },
    },
  },
  plugins: [],
}