export const questionnaireData = [
  {
    id: "goal",
    title: "Define tu Objetivo",
    subtitle: "¿Cuál es tu objetivo principal?",
    stepLabel: "PASO 1 DE 10",
    progress: 0.1,
    options: [
      { id: "gain-muscle", label: "Ganar Masa Muscular", icon: "dumbbell" },
      { id: "lose-fat", label: "Perder Grasa", icon: "flame" },
      { id: "health", label: "Resistencia y Salud", icon: "heart" },
    ],
  },
  {
    id: "experience",
    title: "Tu Punto de Partida",
    subtitle: "¿Qué nivel de experiencia tienes entrenando?",
    stepLabel: "PASO 2 DE 10",
    progress: 0.2,
    options: [
      { id: "beginner", label: "Principiante", icon: "sparkles" },
      { id: "intermediate", label: "Intermedio", icon: "activity" },
      { id: "advanced", label: "Avanzado", icon: "trending-up" },
    ],
  },
  {
    id: "frequency",
    title: "Disponibilidad Semanal",
    subtitle: "¿Cuántos días puedes entrenar?",
    stepLabel: "PASO 3 DE 10",
    progress: 0.3,
    options: [
      { id: "2-3", label: "2 a 3 días", icon: "calendar" },
      { id: "4-5", label: "4 a 5 días", icon: "calendar" },
      { id: "6-7", label: "6 a 7 días", icon: "calendar" },
    ],
  },
  {
    id: "location",
    title: "Dónde Entrenas",
    subtitle: "¿Cuál será tu espacio principal?",
    stepLabel: "PASO 4 DE 10",
    progress: 0.4,
    options: [
      { id: "gym", label: "Gimnasio", icon: "building-2" },
      { id: "home", label: "En Casa", icon: "home" },
      { id: "both", label: "Ambos", icon: "repeat" },
    ],
  },
  {
    id: "time",
    title: "Tiempo por Sesión",
    subtitle: "¿Cuánto tiempo puedes dedicar a cada entrenamiento?",
    stepLabel: "PASO 5 DE 10",
    progress: 0.5,
    options: [
      { id: "30", label: "30 minutos", icon: "clock" },
      { id: "45", label: "45 minutos", icon: "clock" },
      { id: "60", label: "60 minutos o más", icon: "clock" },
    ],
  },
  {
    id: "focus",
    title: "Zona de Enfoque",
    subtitle: "¿Qué parte quieres priorizar?",
    stepLabel: "PASO 6 DE 10",
    progress: 0.6,
    options: [
      { id: "upper", label: "Torso y brazos", icon: "arrow-up" },
      { id: "lower", label: "Piernas y glúteos", icon: "arrow-down" },
      { id: "full-body", label: "Cuerpo completo", icon: "move" },
    ],
  },
  {
    id: "cardio",
    title: "Condición Cardiovascular",
    subtitle: "¿Qué tanto cardio quieres incluir?",
    stepLabel: "PASO 7 DE 10",
    progress: 0.7,
    options: [
      { id: "low", label: "Poco o nada", icon: "slash" },
      { id: "medium", label: "Moderado", icon: "wind" },
      { id: "high", label: "Alto", icon: "zap" },
    ],
  },
  {
    id: "discipline",
    title: "Preferencia de Ritmo",
    subtitle: "¿Qué estilo de entrenamiento prefieres?",
    stepLabel: "PASO 8 DE 10",
    progress: 0.8,
    options: [
      { id: "steady", label: "Constante", icon: "circle" },
      { id: "intense", label: "Intenso", icon: "flame" },
      { id: "balanced", label: "Equilibrado", icon: "scale" },
    ],
  },
  {
    id: "nutrition",
    title: "Hábitos de Alimentación",
    subtitle: "¿Qué tan listo estás para acompañar el plan con tu dieta?",
    stepLabel: "PASO 9 DE 10",
    progress: 0.9,
    options: [
      { id: "ready", label: "Muy listo", icon: "check-circle" },
      { id: "learning", label: "Estoy aprendiendo", icon: "book-open" },
      { id: "help", label: "Necesito guía", icon: "help-circle" },
    ],
  },
  {
    id: "commitment",
    title: "Compromiso Personal",
    subtitle: "¿Qué tan comprometido estás con tu progreso?",
    stepLabel: "PASO 10 DE 10",
    progress: 1,
    options: [
      { id: "high-commitment", label: "100% comprometido", icon: "target" },
      { id: "medium-commitment", label: "Voy paso a paso", icon: "footprints" },
      { id: "starter", label: "Quiero empezar hoy", icon: "play" },
    ],
  },
];