export const questionnaireData = [
  {
    id: "gender",
    title: "Tu Perfil Biométrico",
    subtitle: "¿Cuál es tu género biológico?",
    stepLabel: "PASO 1 DE 18",
    progress: 1/18,
    options: [
      { id: "male", label: "Masculino", icon: "user" },
      { id: "female", label: "Femenino", icon: "user" },
      { id: "other", label: "Prefiero no decirlo", icon: "help-circle" },
    ],
  },
  {
    id: "age",
    title: "¿Qué edad tienes?",
    subtitle: "Rango de edad",
    stepLabel: "PASO 2 DE 18",
    progress: 2/18,
    options: [
      { id: "18-25", label: "18 a 25 años", icon: "calendar" },
      { id: "26-35", label: "26 a 35 años", icon: "calendar" },
      { id: "36-45", label: "36 a 45 años", icon: "calendar" },
      { id: "46+", label: "46 años o más", icon: "calendar" },
    ],
  },
  {
    id: "weight",
    title: "Tu Peso Actual",
    subtitle: "¿Cuál es tu peso aproximado?",
    stepLabel: "PASO 3 DE 18",
    progress: 3/18,
    options: [
      { id: "light", label: "Menos de 60 kg", icon: "minus" },
      { id: "normal", label: "60 a 80 kg", icon: "circle" },
      { id: "heavy", label: "80 a 100 kg", icon: "trending-up" },
      { id: "very-heavy", label: "Más de 100 kg", icon: "trending-up" },
    ],
  },
  {
    id: "height",
    title: "Tu Estatura",
    subtitle: "¿Cuál es tu estatura aproximada?",
    stepLabel: "PASO 4 DE 18",
    progress: 4/18,
    options: [
      { id: "short", label: "Menos de 160 cm", icon: "minus" },
      { id: "normal", label: "160 a 175 cm", icon: "circle" },
      { id: "tall", label: "175 a 190 cm", icon: "arrow-up" },
      { id: "very-tall", label: "Más de 190 cm", icon: "arrow-up" },
    ],
  },
  {
    id: "experience",
    title: "Tu Punto de Partida",
    subtitle: "¿Qué nivel de experiencia tienes entrenando?",
    stepLabel: "PASO 5 DE 18",
    progress: 5/18,
    options: [
      { id: "beginner", label: "Principiante", icon: "sparkles" },
      { id: "intermediate", label: "Intermedio", icon: "activity" },
      { id: "advanced", label: "Avanzado", icon: "trending-up" },
    ],
  },
  {
    id: "goal",
    title: "Define tu Objetivo",
    subtitle: "¿Cuál es tu objetivo principal de entrenamiento?",
    stepLabel: "PASO 6 DE 18",
    progress: 6/18,
    options: [
      { id: "gain-muscle", label: "Ganar Masa Muscular", icon: "dumbbell" },
      { id: "lose-fat", label: "Perder Grasa", icon: "flame" },
      { id: "health", label: "Resistencia y Salud", icon: "heart" },
    ],
  },
  {
    id: "focusArea",
    title: "Zona de Enfoque Principal",
    subtitle: "¿En qué zona quieres poner más énfasis?",
    stepLabel: "PASO 7 DE 18",
    progress: 7/18,
    options: [
      { id: "upper-body", label: "Tren Superior", icon: "arrow-up" },
      { id: "lower-body", label: "Tren Inferior", icon: "arrow-down" },
      { id: "full-body", label: "Cuerpo Completo", icon: "move" },
    ],
  },
  {
    id: "shortTermGoal",
    title: "Meta a Corto Plazo",
    subtitle: "¿Tienes una meta específica en mente?",
    stepLabel: "PASO 8 DE 18",
    progress: 8/18,
    options: [
      { id: "first-pull-up", label: "Mi primera flexión/dominada", icon: "target" },
      { id: "more-weight", label: "Cargar más peso", icon: "trending-up" },
      { id: "more-active", label: "Ser más activo/a", icon: "zap" },
    ],
  },
  {
    id: "daysPerWeek",
    title: "Días de Entrenamiento",
    subtitle: "¿De cuántos días dispones para entrenar a la semana?",
    stepLabel: "PASO 9 DE 18",
    progress: 9/18,
    options: [
      { id: "2", label: "2 días", icon: "calendar" },
      { id: "3", label: "3 días", icon: "calendar" },
      { id: "4", label: "4 días", icon: "calendar" },
      { id: "5+", label: "5 o más días", icon: "calendar" },
    ],
  },
  {
    id: "sessionDuration",
    title: "Duración de Sesión",
    subtitle: "¿Cuánto tiempo puedes dedicar a cada entrenamiento?",
    stepLabel: "PASO 10 DE 18",
    progress: 10/18,
    options: [
      { id: "less-45", label: "Menos de 45 min", icon: "clock" },
      { id: "45-75", label: "45 a 75 min", icon: "clock" },
      { id: "more-90", label: "Más de 90 min", icon: "clock" },
    ],
  },
  {
    id: "trainingLocation",
    title: "Lugar de Entrenamiento",
    subtitle: "¿Dónde realizarás tus entrenamientos principalmente?",
    stepLabel: "PASO 11 DE 18",
    progress: 11/18,
    options: [
      { id: "commercial-gym", label: "Gimnasio comercial", icon: "building-2" },
      { id: "home-gym", label: "Gimnasio en casa", icon: "home" },
      { id: "no-equipment", label: "Ambos", icon: "move" },
    ],
  },
  {
    id: "equipmentPreference",
    title: "Preferencia de Equipo",
    subtitle: "¿Qué herramientas de entrenamiento prefieres usar?",
    stepLabel: "PASO 12 DE 18",
    progress: 12/18,
    options: [
      { id: "machines", label: "Máquinas guiadas", icon: "grid" },
      { id: "free-weights", label: "Pesos libres", icon: "droplet" },
      { id: "mixed", label: "Una mezcla de ambos", icon: "repeat" },
    ],
  },
  {
    id: "activeInjury",
    title: "Limitaciones Físicas",
    subtitle: "¿Tienes alguna lesión activa?",
    stepLabel: "PASO 13 DE 18",
    progress: 13/18,
    options: [
      { id: "back", label: "Espalda/Lumbar", icon: "alert-circle" },
      { id: "knees", label: "Rodillas", icon: "alert-circle" },
      { id: "shoulders", label: "Hombros", icon: "alert-circle" },
      { id: "none", label: "Ninguna", icon: "check-circle" },
    ],
  },
  {
    id: "dailyActivity",
    title: "Nivel de Actividad Diaria",
    subtitle: "¿Cuál es tu nivel de actividad fuera del ejercicio?",
    stepLabel: "PASO 14 DE 18",
    progress: 14/18,
    options: [
      { id: "sedentary", label: "Sedentario", icon: "minus" },
      { id: "moderate", label: "Moderado", icon: "circle" },
      { id: "very-active", label: "Muy activo", icon: "zap" },
    ],
  },
  {
    id: "techniqueVideos",
    title: "Videos de Técnica",
    subtitle: "¿Qué tan importante es ver videos de técnica?",
    stepLabel: "PASO 15 DE 18",
    progress: 15/18,
    options: [
      { id: "very-important", label: "Muy importante", icon: "book-open" },
      { id: "new-exercises", label: "Solo ejercicios nuevos", icon: "help-circle" },
      { id: "not-needed", label: "No lo necesito", icon: "check-circle" },
    ],
  },
  {
    id: "mainObstacle",
    title: "Tu Mayor Obstáculo",
    subtitle: "¿Cuál ha sido tu mayor obstáculo antes?",
    stepLabel: "PASO 16 DE 18",
    progress: 16/18,
    options: [
      { id: "not-know", label: "No sé qué hacer", icon: "help-circle" },
      { id: "motivation", label: "Falta de motivación", icon: "heart" },
      { id: "boring", label: "Rutinas aburridas", icon: "zap" },
    ],
  },
  {
    id: "unitPreference",
    title: "Unidad de Medida",
    subtitle: "¿Prefieres kilogramos o libras?",
    stepLabel: "PASO 17 DE 18",
    progress: 17/18,
    options: [
      { id: "kg", label: "Kilogramos (kg)", icon: "weight" },
      { id: "lb", label: "Libras (lb)", icon: "weight" },
    ],
  },
  {
    id: "disclaimer",
    title: "Aviso de Responsabilidad",
    subtitle: "¿Entiendes que esta app es una guía profesional?",
    stepLabel: "PASO 18 DE 18",
    progress: 1,
    options: [
      { id: "accept", label: "Sí, acepto", icon: "check-circle" },
      { id: "decline", label: "No acepto", icon: "x-circle" },
    ],
  },
];